version: "3"
services:
  node-frontend:
    image: nodeapp
    build: .
    environment:
      NODE_ENV: development
      APP_HOST: 0.0.0.0
    ports:
      - 3000:3000
  jcrud:
    image: jcrud
    build:
      context: ./jcrud
    ports:
      - 5000:5000
  redis:
    image: redis
    ports:
      - 6379:6379
